[[constraint]]
  name = "github.com/beevik/etree"
  version = "1.1.0"

[[constraint]]
  name = "github.com/jonboulle/clockwork"
  version = "0.1.0"

[[constraint]]
  name = "github.com/russellhaering/gosaml2"
  version = "0.3.1"

[[constraint]]
  branch = "master"
  name = "github.com/russellhaering/goxmldsig"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[prune]
  go-tests = true
  unused-packages = true
